name: Java

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Install dependencies (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get install libopenslide0-dev ninja-build
        # Ubuntu 22.04 packages Meson 0.61
        pip install --user meson
    - name: Install dependencies (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install meson openslide
    - name: Build
      run: |
        meson setup builddir --prefix=$HOME
        meson compile -C builddir
        meson install -C builddir
    - name: Smoke test
      run: java -cp builddir/openslide.jar org.openslide.TestCLI fixtures/small.svs
